### ISSUE TITLE
Error downloading object: CADB_CADC/Library/FIR-2-3Hz-40.mat (98d54bc)

### ISSUE THREAD

**Issue by rmndrs89** [mobilise-d/Mobilise-D-TVS-Recommended-Algorithms#1]
I was trying to clone this repo to my local machine, yet it throws an error for the `FIR-2-3Hz-40.mat` file.

```bash
$ git clone https://github.com/mobilise-d/Mobilise-D-TVS-Recommended-Algorithms.git
Cloning into 'Mobilise-D-TVS-Recommended-Algorithms'...
remote: Enumerating objects: 136, done.
remote: Counting objects: 100% (136/136), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 136 (delta 44), reused 136 (delta 44), pack-reused 0
Receiving objects: 100% (136/136), 881.38 KiB | 2.00 MiB/s, done.
Resolving deltas: 100% (44/44), done.
Updating files: 100% (77/77), done.
Downloading CADB_CADC/Library/FIR-2-3Hz-40.mat (725 B)
Error downloading object: CADB_CADC/Library/FIR-2-3Hz-40.mat (98d54bc): Smudge error: Error downloading CADB_CADC/Library/FIR-2-3Hz-40.mat (98d54bcb01154a8ed65aceb5397f96e914bbf48dfce8dfd6fab77fe93d3727a1): [98d54bcb01154a8ed65aceb5397f96e914bbf48dfce8dfd6fab77fe93d3727a1] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to D:\Projects\Mobilise-D-TVS-Recommended-Algorithms\.git\lfs\logs\20230615T154950.7543025.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: CADB_CADC/Library/FIR-2-3Hz-40.mat: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

The error message suggest to check the following:
```bash
$ git lfs logs last
git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
git version 2.33.0.windows.2

$ git-lfs.exe filter-process
Error downloading object: CADB_CADC/Library/FIR-2-3Hz-40.mat (98d54bc): Smudge error: Error downloading CADB_CADC/Library/FIR-2-3Hz-40.mat (98d54bcb01154a8ed65aceb5397f96e914bbf48dfce8dfd6fab77fe93d3727a1): [98d54bcb01154a8ed65aceb5397f96e914bbf48dfce8dfd6fab77fe93d3727a1] Object does not exist on the server: [404] Object does not exist on the server
```

**Is there another possibility to get ahold on this file?** The FIR filter is used in almost all downstream algorithms and therefore essential to run any analysis.

Best regards,
Robbin

**Comment by pvand** [comment]
I have the same issue. I tried using:
`git lfs clone https://github.com/mobilise-d/Mobilise-D-TVS-Recommended-Algorithms.git`

But it results in the following error:
```
Receiving objects:  79% (108/136), 612.00 KiB | 564.00 KiB/sused 0
Receiving objects: 100% (136/136), 881.38 KiB | 623.00 KiB/s, done.
Resolving deltas: 100% (44/44), done.
[544a66db9fd0af1d4826f66ba61653aa25e91d1db7451e64475708aec45bcf5a] Object does not exist on the server: [404] Object does not exist on the server
[2072f642c62e325b1983b2e30426351aec5c5959ff65887b38fbd9d0df97d2d4] Object does not exist on the server: [404] Object does not exist on the server
[d9b9ff69dabea1d673844a03aff5a184f56c39b0533e46d8eaa90fd11c178370] Object does not exist on the server: [404] Object does not exist on the server
[0aec0756a79e782808f95bf001e725fffc3bafa5d7847a6e00a3f2579033701d] Object does not exist on the server: [404] Object does not exist on the server
[98d54bcb01154a8ed65aceb5397f96e914bbf48dfce8dfd6fab77fe93d3727a1] Object does not exist on the server: [404] Object does not exist on the server
[236abb24b2bd47a9b45dd37d192fc13b7234aa2070be80fb0d845232249bb351] Object does not exist on the server: [404] Object does not exist on the server
Failed to fetch some objects from 'https://github.com/mobilise-d/Mobilise-D-TVS-Recommended-Algorithms.git/info/lfs'
```

Has there been a solution to this issue already?

Kind regards,
Pieter

**Comment by sil-silvia** [comment]
Hi All,
Apologies, the attached .mat file (zipped folder with FIR-2-3Hz-40.mat) should be fixing the issue (if you copy it in your working folder).

Best,
Silvia
[FIR-2-3Hz-40.zip](https://github.com/mobilise-d/Mobilise-D-TVS-Recommended-Algorithms/files/12315639/FIR-2-3Hz-40.zip)

**Comment by cvlng** [comment]
Hi Silvia,
I still have the same problem with the new .mat file in my working folder. 

`[544a66db9fd0af1d4826f66ba61653aa25e91d1db7451e64475708aec45bcf5a] Object does not exist on the server: [404] Object does not exist on the server
[2072f642c62e325b1983b2e30426351aec5c5959ff65887b38fbd9d0df97d2d4] Object does not exist on the server: [404] Object does not exist on the server
[d9b9ff69dabea1d673844a03aff5a184f56c39b0533e46d8eaa90fd11c178370] Object does not exist on the server: [404] Object does not exist on the server
[0aec0756a79e782808f95bf001e725fffc3bafa5d7847a6e00a3f2579033701d] Object does not exist on the server: [404] Object does not exist on the server
[98d54bcb01154a8ed65aceb5397f96e914bbf48dfce8dfd6fab77fe93d3727a1] Object does not exist on the server: [404] Object does not exist on the server
[236abb24b2bd47a9b45dd37d192fc13b7234aa2070be80fb0d845232249bb351] Object does not exist on the server: [404] Object does not exist on the server
Failed to fetch some objects from 'https://github.com/mobilise-d/Mobilise-D-TVS-Recommended-Algorithms.git/info/lfs'
`

Is there another way to solve this issue?

Kind regards,
Charlotte

**Comment by sil-silvia** [comment]
Hi Charlotte,
Sorry to hear this.
From my understanding the .mat file solved the issue (I had same conversation with another researcher a while ago).
I suggest you download the files again and add the .mat file. The error message seems to have issue with “fetching files” from online and issues with your server.

Cam downloaded and tested the algorithms locally and all went fine, in case please contact him (cc).

Best,
Silvia
