### ISSUE TITLE
[ERROR] Unable to read MAT-file for the step length estimation TrainedModels

### ISSUE THREAD

**Issue by rmndrs89** [mobilise-d/Mobilise-D-TVS-Recommended-Algorithms#2]
Hi all,

when I try to load the .mat file for the step length estimation, I run into 
```
Error using load
Unable to read MAT-file
D:\Documents\MATLAB\Mobilise-D-TVS-Recommended-Algorithms\SLA_SLB\Library\TrainedModels\SLmodel_MS_MS.mat.
Not a binary MAT-file. Try load -ASCII to read as text.
```

Then, when load with `-ASCII` I get:
```
Error using load
Number of columns on line 8 of ASCII file
D:\Documents\MATLAB\Mobilise-D-TVS-Recommended-Algorithms\SLA_SLB\Library\TrainedModels\SLmodel_MS_MS.mat
must be the same as previous lines.
```

Is there any easy way to circumvent this problem? 

It applies to all given **SLmodel_*.mat** files.

Best regards,
Robbin

**Comment by CJkirk105** [comment]
Hi Robbin, 

I've uploaded an updated version of the SL_MS_MS - Model to the repository - please let me know if that works/doesn't work

thanks 

CAm

**Comment by jaderonmu** [comment]
Hi Cam,

I still have the same problem with the SL_MS_MS model. I keep getting this error:

"
Not a binary MAT-file. Try load -ASCII to read as text.

Error in STRIDELEN (line 92)
load(modeladd);

"
Could you share the file?

Thanks,
Joseph

**Comment by CJkirk105** [comment]
Hello, no - problem, can you please share your email? Then I can share the file

**Comment by jaderonmu** [comment]
Here is my email: jaderonmu@unomaha.edu

Thanks!
